<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:extns="http://www.mycorelogic.com/CLE/Public/Log.xsd" xmlns:tns="http://www.mycorelogic.com/wsdl/PublishLog" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="PublishLog" targetNamespace="http://www.mycorelogic.com/wsdl/PublishLog">
  <wsdl:import namespace="http://www.mycorelogic.com/CLE/Public/Log.xsd"/>
  <wsdl:message name="Log">
    <wsdl:part element="extns:Log" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="Log">
    <wsdl:operation name="PublishLog">
      <wsdl:input message="tns:Log" name="PublishLoginput"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
