<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:extns="http://www.mycorelogic.com/CLE/Public/Exception.xsd" xmlns:tns="http://www.mycorelogic.com/wsdl/PublishException" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="PublishException" targetNamespace="http://www.mycorelogic.com/wsdl/PublishException">
  <wsdl:import namespace="http://www.mycorelogic.com/CLE/Public/Exception.xsd"/>
  <wsdl:message name="Exception">
    <wsdl:part element="extns:Exception" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="Exception">
    <wsdl:operation name="PublishException">
      <wsdl:input message="tns:Exception" name="PublishExceptioninput"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
